################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../MQTTClient.c \
../app.c \
../cellular.c \
../cellular_common.c \
../cellular_internet.c \
../cellular_parse_operators.c \
../cellular_parse_physical.c \
../main.c \
../mqtt_handler.c \
../my_printf_lib.c \
../serial_io_efm32pg12.c \
../serial_io_linux.c \
../socket_linux_modem.c \
../test_cellular.c \
../utils.c 

OBJS += \
./MQTTClient.o \
./app.o \
./cellular.o \
./cellular_common.o \
./cellular_internet.o \
./cellular_parse_operators.o \
./cellular_parse_physical.o \
./main.o \
./mqtt_handler.o \
./my_printf_lib.o \
./serial_io_efm32pg12.o \
./serial_io_linux.o \
./socket_linux_modem.o \
./test_cellular.o \
./utils.o 

C_DEPS += \
./MQTTClient.d \
./app.d \
./cellular.d \
./cellular_common.d \
./cellular_internet.d \
./cellular_parse_operators.d \
./cellular_parse_physical.d \
./main.d \
./mqtt_handler.d \
./my_printf_lib.d \
./serial_io_efm32pg12.d \
./serial_io_linux.d \
./socket_linux_modem.d \
./test_cellular.d \
./utils.d 


# Each subdirectory must supply rules for building sources it contributes
MQTTClient.o: ../MQTTClient.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32PG12B500F1024GL125=1' '-DSL_BOARD_NAME="BRD2501A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\Device\SiliconLabs\EFM32PG12B\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\board\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\button\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\CMSIS\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\device_init\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\dmd" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emlib\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\iostream\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\leddrv\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\src\ls013b7dh03" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc\memlcd_usart" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\power_manager\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\toolchain\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\system\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\sleeptimer\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\udelay\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\autogen" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\config" -Os -Wall -Wextra -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"MQTTClient.d" -MT"MQTTClient.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

app.o: ../app.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32PG12B500F1024GL125=1' '-DSL_BOARD_NAME="BRD2501A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\Device\SiliconLabs\EFM32PG12B\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\board\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\button\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\CMSIS\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\device_init\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\dmd" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emlib\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\iostream\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\leddrv\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\src\ls013b7dh03" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc\memlcd_usart" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\power_manager\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\toolchain\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\system\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\sleeptimer\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\udelay\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\autogen" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\config" -Os -Wall -Wextra -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"app.d" -MT"app.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

cellular.o: ../cellular.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32PG12B500F1024GL125=1' '-DSL_BOARD_NAME="BRD2501A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\Device\SiliconLabs\EFM32PG12B\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\board\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\button\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\CMSIS\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\device_init\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\dmd" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emlib\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\iostream\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\leddrv\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\src\ls013b7dh03" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc\memlcd_usart" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\power_manager\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\toolchain\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\system\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\sleeptimer\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\udelay\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\autogen" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\config" -Os -Wall -Wextra -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"cellular.d" -MT"cellular.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

cellular_common.o: ../cellular_common.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32PG12B500F1024GL125=1' '-DSL_BOARD_NAME="BRD2501A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\Device\SiliconLabs\EFM32PG12B\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\board\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\button\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\CMSIS\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\device_init\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\dmd" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emlib\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\iostream\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\leddrv\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\src\ls013b7dh03" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc\memlcd_usart" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\power_manager\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\toolchain\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\system\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\sleeptimer\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\udelay\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\autogen" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\config" -Os -Wall -Wextra -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"cellular_common.d" -MT"cellular_common.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

cellular_internet.o: ../cellular_internet.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32PG12B500F1024GL125=1' '-DSL_BOARD_NAME="BRD2501A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\Device\SiliconLabs\EFM32PG12B\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\board\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\button\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\CMSIS\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\device_init\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\dmd" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emlib\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\iostream\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\leddrv\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\src\ls013b7dh03" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc\memlcd_usart" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\power_manager\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\toolchain\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\system\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\sleeptimer\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\udelay\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\autogen" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\config" -Os -Wall -Wextra -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"cellular_internet.d" -MT"cellular_internet.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

cellular_parse_operators.o: ../cellular_parse_operators.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32PG12B500F1024GL125=1' '-DSL_BOARD_NAME="BRD2501A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\Device\SiliconLabs\EFM32PG12B\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\board\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\button\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\CMSIS\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\device_init\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\dmd" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emlib\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\iostream\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\leddrv\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\src\ls013b7dh03" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc\memlcd_usart" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\power_manager\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\toolchain\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\system\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\sleeptimer\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\udelay\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\autogen" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\config" -Os -Wall -Wextra -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"cellular_parse_operators.d" -MT"cellular_parse_operators.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

cellular_parse_physical.o: ../cellular_parse_physical.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32PG12B500F1024GL125=1' '-DSL_BOARD_NAME="BRD2501A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\Device\SiliconLabs\EFM32PG12B\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\board\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\button\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\CMSIS\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\device_init\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\dmd" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emlib\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\iostream\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\leddrv\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\src\ls013b7dh03" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc\memlcd_usart" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\power_manager\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\toolchain\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\system\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\sleeptimer\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\udelay\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\autogen" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\config" -Os -Wall -Wextra -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"cellular_parse_physical.d" -MT"cellular_parse_physical.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

main.o: ../main.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32PG12B500F1024GL125=1' '-DSL_BOARD_NAME="BRD2501A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\Device\SiliconLabs\EFM32PG12B\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\board\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\button\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\CMSIS\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\device_init\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\dmd" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emlib\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\iostream\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\leddrv\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\src\ls013b7dh03" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc\memlcd_usart" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\power_manager\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\toolchain\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\system\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\sleeptimer\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\udelay\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\autogen" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\config" -Os -Wall -Wextra -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"main.d" -MT"main.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mqtt_handler.o: ../mqtt_handler.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32PG12B500F1024GL125=1' '-DSL_BOARD_NAME="BRD2501A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\Device\SiliconLabs\EFM32PG12B\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\board\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\button\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\CMSIS\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\device_init\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\dmd" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emlib\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\iostream\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\leddrv\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\src\ls013b7dh03" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc\memlcd_usart" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\power_manager\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\toolchain\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\system\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\sleeptimer\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\udelay\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\autogen" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\config" -Os -Wall -Wextra -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"mqtt_handler.d" -MT"mqtt_handler.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

my_printf_lib.o: ../my_printf_lib.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32PG12B500F1024GL125=1' '-DSL_BOARD_NAME="BRD2501A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\Device\SiliconLabs\EFM32PG12B\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\board\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\button\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\CMSIS\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\device_init\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\dmd" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emlib\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\iostream\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\leddrv\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\src\ls013b7dh03" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc\memlcd_usart" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\power_manager\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\toolchain\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\system\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\sleeptimer\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\udelay\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\autogen" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\config" -Os -Wall -Wextra -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"my_printf_lib.d" -MT"my_printf_lib.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

serial_io_efm32pg12.o: ../serial_io_efm32pg12.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32PG12B500F1024GL125=1' '-DSL_BOARD_NAME="BRD2501A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\Device\SiliconLabs\EFM32PG12B\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\board\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\button\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\CMSIS\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\device_init\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\dmd" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emlib\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\iostream\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\leddrv\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\src\ls013b7dh03" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc\memlcd_usart" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\power_manager\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\toolchain\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\system\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\sleeptimer\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\udelay\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\autogen" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\config" -Os -Wall -Wextra -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"serial_io_efm32pg12.d" -MT"serial_io_efm32pg12.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

serial_io_linux.o: ../serial_io_linux.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32PG12B500F1024GL125=1' '-DSL_BOARD_NAME="BRD2501A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\Device\SiliconLabs\EFM32PG12B\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\board\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\button\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\CMSIS\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\device_init\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\dmd" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emlib\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\iostream\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\leddrv\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\src\ls013b7dh03" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc\memlcd_usart" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\power_manager\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\toolchain\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\system\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\sleeptimer\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\udelay\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\autogen" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\config" -Os -Wall -Wextra -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"serial_io_linux.d" -MT"serial_io_linux.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

socket_linux_modem.o: ../socket_linux_modem.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32PG12B500F1024GL125=1' '-DSL_BOARD_NAME="BRD2501A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\Device\SiliconLabs\EFM32PG12B\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\board\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\button\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\CMSIS\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\device_init\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\dmd" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emlib\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\iostream\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\leddrv\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\src\ls013b7dh03" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc\memlcd_usart" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\power_manager\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\toolchain\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\system\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\sleeptimer\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\udelay\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\autogen" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\config" -Os -Wall -Wextra -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"socket_linux_modem.d" -MT"socket_linux_modem.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

test_cellular.o: ../test_cellular.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32PG12B500F1024GL125=1' '-DSL_BOARD_NAME="BRD2501A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\Device\SiliconLabs\EFM32PG12B\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\board\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\button\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\CMSIS\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\device_init\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\dmd" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emlib\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\iostream\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\leddrv\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\src\ls013b7dh03" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc\memlcd_usart" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\power_manager\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\toolchain\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\system\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\sleeptimer\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\udelay\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\autogen" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\config" -Os -Wall -Wextra -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"test_cellular.d" -MT"test_cellular.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils.o: ../utils.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32PG12B500F1024GL125=1' '-DSL_BOARD_NAME="BRD2501A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\Device\SiliconLabs\EFM32PG12B\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\board\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\button\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\CMSIS\Include" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\device_init\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\dmd" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\common\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emlib\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\middleware\glib\glib" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\iostream\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\driver\leddrv\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\src\ls013b7dh03" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\hardware\driver\memlcd\inc\memlcd_usart" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\power_manager\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\common\toolchain\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\system\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\sleeptimer\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\gecko_sdk_4.0.0\platform\service\udelay\inc" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\autogen" -I"C:\Users\yuval\SimplicityStudio\v5_workspace\ex9\config" -Os -Wall -Wextra -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"utils.d" -MT"utils.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


